### ISSUE TITLE
Website background color

### ISSUE THREAD

**Issue by majedbojan** [Leapat-mukalla/leapat#15]
We need to enhance the current website bg to meet the exact Figma

https://www.figma.com/design/cUuo0esdZ5YgTWMFAMTgnO/leapat?node-id=0-1&t=Vp7Tj5xHRmF2yJPe-0

**Comment by majedbojan** [comment]
@ZainbMohammed can we pick up this

**Comment by mhmdAljefri** [comment]
https://github.com/Leapat-mukalla/leapat/pull/21
