### ISSUE TITLE
Footer responsive

### ISSUE THREAD

**Issue by majedbojan** [Leapat-mukalla/leapat#20]
The footer is not responsive right now we need to make it responsive

This should be the mobile version

<img width="502" alt="Screenshot 2024-08-24 at 5 15 17 PM" src="https://github.com/user-attachments/assets/14498cc7-39a5-4759-9180-372e6400efa2">

https://www.figma.com/design/cUuo0esdZ5YgTWMFAMTgnO/leapat?node-id=386-804&t=6LraTP7tH1cIMNaf-0

**Comment by mhmdAljefri** [comment]
@majedbojan I will take this
